
BR_ITEM_NAMES_FROM_MODELS = {
    {"models/foodnhouseholditems/pizzab.mdl", "Pizza"},
    {"models/foodnhouseholditems/sandwich.mdl", "Sandwich"},
    {"models/foodnhouseholditems/cookies.mdl", "Cookies"},
    {"models/foodnhouseholditems/mcdburgerbox.mdl", "Burger"},
    {"models/foodnhouseholditems/icecream1.mdl", "Ice Cream"},
    {"models/foodnhouseholditems/mcdfrenchfries.mdl", "French Fries"},
    {"models/foodnhouseholditems/chipslays.mdl", "Chips"},
    {"models/foodnhouseholditems/wine_white3.mdl", "Wine"},
    {"models/foodnhouseholditems/juice.mdl", "Orange Juice"},
    {"models/foodnhouseholditems/newspaper2.mdl", "Document"},
    {"models/cpthazama/scp/500.mdl", "SCP-500"},
}

BR_ITEM_DESCRIPTIONS = {
	-- SWEP ITEMS
	item_battery_9v = {desc = "Generic battery used in electronic devices"},
	item_c4 = {desc = "Remotely armed explosive charge"},
	item_gasmask = {desc = "Protects you from toxic gases"},
	item_gasmask2 = {desc = "Protects you from toxic gases, somehow it also keeps you from tiring"},
	item_medkit = {desc = "Field medical kit with several different treatments"},
	item_nvg = {desc = "Night vision goggles, useful in dark areas"},
	item_nvg2 = {desc = "Night vision goggles, useful in dark areas"},
	item_nvg3 = {desc = "Night vision goggles that also highlight living creatures"},
	item_nvg_military = {desc = "Military night vision goggles with a wider, clearer view"},
	item_pills = {desc = "Pills that restore your sanity"},
	item_radio = {desc = "Two-way radio for talking to nearby channels"},
	item_radio2 = {desc = "A radio picking up an endless coded broadcast"},
	keycard_master = {desc = "Not a keycard at all, but very useful"},
	keycard_playing = {desc = "Not a keycard at all, but very useful"},
	keycard_level1 = {desc = "Clearance level 1"},
	keycard_level2 = {desc = "Clearance level 2"},
	keycard_level3 = {desc = "Clearance level 3"},
	keycard_level4 = {desc = "Clearance level 4"},
	keycard_level5 = {desc = "Clearance level 5"},
	keycard_omni = {desc = "Clearance for every door in the facility"},

	-- GUNS
	kanade_tfa_acr       = {desc = "Modern, balanced assault rifle"},
	kanade_tfa_ak12      = {desc = "Advanced Russian assault rifle"},
	kanade_tfa_ak103     = {desc = "Reliable heavy-hitting AK variant"},
	kanade_tfa_ar15      = {desc = "Light, accurate civilian rifle"},
	kanade_tfa_aug       = {desc = "Bullpup assault rifle with precision"},
	kanade_tfa_beretta   = {desc = "Trusted 9mm sidearm"},
	kanade_tfa_cobra     = {desc = "Compact and fierce revolver"},
	kanade_tfa_colt      = {desc = "Classic American handgun"},
	kanade_tfa_cz805     = {desc = "Czech-made modular rifle"},
	kanade_tfa_deagle    = {desc = "Iconic high-caliber hand cannon"},
	kanade_tfa_dsr1      = {desc = "Elite long-range sniper rifle"},
	kanade_tfa_f90mbr    = {desc = "Compact bullpup assault rifle"},
	kanade_tfa_famas     = {desc = "French burst-fire rifle"},
	kanade_tfa_fnfal     = {desc = "Battle rifle with stopping power"},
	kanade_tfa_fnp45     = {desc = "Large caliber semi-auto pistol"},
	kanade_tfa_g3        = {desc = "Classic 7.62 battle rifle"},
	kanade_tfa_g36       = {desc = "German assault rifle staple"},
	kanade_tfa_glock     = {desc = "Fast and reliable handgun"},
	kanade_tfa_gry       = {desc = "Modern tactical rifle"},
	kanade_tfa_hkg36c    = {desc = "Compact G36 carbine"},
	kanade_tfa_krissv    = {desc = "High-tech .45 SMG"},
	kanade_tfa_l85a2     = {desc = "British bullpup rifle"},
	kanade_tfa_m4a1      = {desc = "Classic American assault rifle"},
	kanade_tfa_m14       = {desc = "Classic 7.62 battle rifle"},
	kanade_tfa_m40a1     = {desc = "Precision bolt-action sniper"},
	kanade_tfa_m249      = {desc = "Squad automatic machine gun"},
	kanade_tfa_m1014     = {desc = "Rapid semi-auto shotgun"},
	kanade_tfa_makarov   = {desc = "Compact Soviet sidearm"},
	kanade_tfa_mk18      = {desc = "CQB carbine variant"},
	kanade_tfa_mosin     = {desc = "Old but deadly bolt-action"},
	kanade_tfa_mp5a5     = {desc = "Classic German SMG"},
	kanade_tfa_mp5k      = {desc = "Compact submachine gun"},
	kanade_tfa_mp7       = {desc = "PDW with high fire rate"},
	kanade_tfa_p90       = {desc = "Futuristic high-capacity SMG"},
	kanade_tfa_remington = {desc = "Bolt-Action sniper rifle"},
	kanade_tfa_rpg       = {desc = "Devastating rocket launcher"},
	kanade_tfa_sawedoff  = {desc = "Short, brutal shotgun"},
	kanade_tfa_scar      = {desc = "Versatile modern rifle"},
	kanade_tfa_scarh     = {desc = "Heavy-hitting SCAR variant"},
	kanade_tfa_sg552     = {desc = "Swiss assault rifle"},
	kanade_tfa_sterling  = {desc = "Vintage British SMG"},
	kanade_tfa_tac338    = {desc = "High-power sniper rifle"},
	kanade_tfa_ump45     = {desc = "Reliable .45 submachine gun"},
	kanade_tfa_vhs       = {desc = "Croatian bullpup assault rifle"},
	kanade_tfa_m16a4     = {desc = "Burst-fire assault rifle"},
	kanade_tfa_m590      = {desc = "Hard-hitting pump shotgun"},
	kanade_tfa_rpk       = {desc = "Russian squad support LMG"},

	kanade_tfa_pipe      = {desc = "Improvised blunt weapon"},
	kanade_tfa_chainsaw  = {desc = "Brutal powered cutting tool"},
	kanade_tfa_axe       = {desc = "Heavy firefighter’s axe"},
	kanade_tfa_crowbar   = {desc = "Versatile demolition tool"},
	kanade_tfa_stunbaton = {desc = "Shock-delivering baton"},
	
	-- RANDOM ITEMS
	severed_hand = {name = "Severed Hand", desc = "Disgusting, but it still holds a keycard", mdl = "models/cultist/items/hand_keycard/hand_keycard.mdl"},

	flashlight_cheap = {name = "Regular Flashlight", desc = "Portable hand-held electric light", mdl = "models/weapons/tfa_nmrih/w_item_maglite.mdl"},
	flashlight_normal = {name = "Heavy Duty Flashlight", desc = "Portable hand-held electric light, brighter and longer lasting", mdl = "models/weapons/tfa_nmrih/w_item_maglite.mdl"},
	flashlight_tactical = {name = "Tactical Flashlight", desc = "Portable hand-held electric light, the brightest of them all", mdl = "models/weapons/tfa_nmrih/w_item_maglite.mdl"},

	device_cameras = {name = "WCR [Cameras]", desc = "Install it in a terminal to check the cameras", mdl = "models/props_lab/reciever01c.mdl"},
	cup = {desc = "Just a cup", mdl = "models/mishka/models/plastic_cup.mdl"},
	document = {desc = "Readable document"},
	conf_folder = {name = "Confidential Folder", desc = "Folder of confidential information", mdl = "models/scp_documents/secret_document.mdl"},
	coin = {name = "Coin", desc = "Just a shiny coin, some machines take them", mdl = "models/cultist/items/coin/coin.mdl"},
	lockpick = {name = "Lockpick", desc = "Universal lockpick for opening doors and crates"},
	crafting_toolbox = {name = "Toolbox", desc = "Toolbox holding a few useful spare parts", mdl = "models/cultist/items/toolbox/tool_box.mdl"},

	battery9v = {name = "9V Battery", desc = "Generic battery used in electronic devices", mdl = "models/mishka/models/battery.mdl"},

	-- AMMO
	ammo_pistol16 = {name = "Pistol Ammo Box 16", desc = "A box of 16 pistol rounds", mdl = "models/Items/357ammo.mdl"},
	ammo_pistol32 = {name = "Pistol Ammo Box 32", desc = "A box of 32 pistol rounds", mdl = "models/Items/357ammo.mdl"},
	ammo_pistol64 = {name = "Pistol Ammo Box 64", desc = "A box of 64 pistol rounds", mdl = "models/Items/357ammo.mdl"},
	ammo_pistol128 = {name = "Pistol Ammo Box 128", desc = "A box of 128 pistol rounds", mdl = "models/Items/357ammo.mdl"},
	ammo_smg30 = {name = "SMG Ammo Box 30", desc = "A box of 30 SMG rounds", mdl = "models/Items/BoxMRounds.mdl"},
	ammo_smg60 = {name = "SMG Ammo Box 60", desc = "A box of 60 SMG rounds", mdl = "models/Items/BoxMRounds.mdl"},
	ammo_smg90 = {name = "SMG Ammo Box 90", desc = "A box of 90 SMG rounds", mdl = "models/Items/BoxMRounds.mdl"},
	ammo_smg120 = {name = "SMG Ammo Box 120", desc = "A box of 120 SMG rounds", mdl = "models/Items/BoxMRounds.mdl"},
	ammo_rifle30 = {name = "Rifle Ammo Box 30", desc = "A box of 30 rifle rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_rifle60 = {name = "Rifle Ammo Box 60", desc = "A box of 60 rifle rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_rifle90 = {name = "Rifle Ammo Box 90", desc = "A box of 90 rifle rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_rifle120 = {name = "Rifle Ammo Box 120", desc = "A box of 120 rifle rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_shotgun10 = {name = "Shotgun Ammo Box 10", desc = "A box of 10 shotgun shells", mdl = "models/Items/BoxBuckshot.mdl"},
	ammo_shotgun20 = {name = "Shotgun Ammo Box 20", desc = "A box of 20 shotgun shells", mdl = "models/Items/BoxBuckshot.mdl"},
	ammo_shotgun30 = {name = "Shotgun Ammo Box 30", desc = "A box of 30 shotgun shells", mdl = "models/Items/BoxBuckshot.mdl"},
	ammo_sniper5 = {name = "Sniper Ammo Box 5", desc = "A box of 5 sniper rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_sniper10 = {name = "Sniper Ammo Box 10", desc = "A box of 10 sniper rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_sniper20 = {name = "Sniper Ammo Box 20", desc = "A box of 20 sniper rounds", mdl = "models/Items/BoxSRounds.mdl"},
	ammo_sniper40 = {name = "Sniper Ammo Box 40", desc = "A box of 40 sniper rounds", mdl = "models/Items/BoxSRounds.mdl"},

	-- DRINKS
	drink_bottle_water = {name = "Water Bottle", desc = "A bottle of purified water", mdl = "models/props/cs_office/Water_bottle.mdl"},
	drink_soda = {name = "Can of Soda", desc = "A can of tasty soda", mdl = "models/props_junk/PopCan01a.mdl"},
    drink_orange_juice = {name = "Orange Juice", desc = "A big box of orange juice", mdl = "models/foodnhouseholditems/juice.mdl"},
    drink_wine = {name = "Wine", desc = "An expensive bottle of wine", mdl = "models/foodnhouseholditems/wine_white3.mdl"},

	-- FOOD
	food_cookies = {name = "Cookies", desc = "A box of tasty cookies", mdl = "models/foodnhouseholditems/cookies.mdl"},
	food_sandwich = {name = "Sandwich", desc = "Ham, lettuce and tomatoes", mdl = "models/foodnhouseholditems/sandwich.mdl"},
	food_burger = {name = "Burger", desc = "A big burger in a box", mdl = "models/foodnhouseholditems/mcdburgerbox.mdl"},
	food_icecream = {name = "Ice Cream", desc = "A box of cold ice cream", mdl = "models/foodnhouseholditems/icecream1.mdl"},
	food_frenchfries = {name = "French Fries", desc = "Hot and crispy french fries", mdl = "models/foodnhouseholditems/mcdfrenchfries.mdl"},
	food_chips = {name = "Chips", desc = "Just a bag of chips", mdl = "models/foodnhouseholditems/chipslays.mdl"},
	food_pizzaslice = {name = "Pizza Slice", desc = "A single slice of pizza", mdl = "models/foodnhouseholditems/pizzaslice.mdl"},
    food_pizza = {name = "Pizza", desc = "A whole pizza, use it to cut 8 slices", mdl = "models/foodnhouseholditems/pizzab.mdl"},

	-- MEDICAL
	scp_420 = {name = "SCP-420-J", desc = "The Best ████ in the World", mdl = "models/mishka/models/scp420.mdl"},
	scp_500 = {name = "SCP-500", desc = "A pill that heals all wounds", mdl = "models/cpthazama/scp/500.mdl"},
	syringe = {name = "Syringe", desc = "A shot of adrenaline, restores your stamina", mdl = "models/mishka/models/syringe.mdl"},
	personal_medkit = {name = "Personal Medkit", desc = "Heals your wounds and stops bleeding, has 3 uses", mdl = "models/cultist/items/medkit/w_medkit.mdl"},
	antibiotics = {name = "Antibiotics", desc = "Cures infections and calms you down a little", mdl =  "models/cultist/items/painpills/w_painpills.mdl"},
	eyedrops = {name = "Eyedrops", desc = "Saline drops, they help you see in the dark for a while", mdl = "models/cultist/items/eyedrops/eyedrops.mdl"},
	ssri_pills = {name = "SSRI Pills", desc = "Pills that restore your sanity", mdl = "models/cultist/items/painpills/w_painpills.mdl"},
}
