
br2_add_cvar("br2_time_preparing", "25", "Time in seconds for the preparing phase")
br2_add_cvar("br2_time_round", "1320", "Total length of the round in seconds")
br2_add_cvar("br2_time_postround", "30", "Length of the post-round time")
br2_add_cvar("br2_time_mtf_spawn", "400", "Time counted from round start before MTF are allowed to spawn")
br2_add_cvar("br2_time_ci_spawn", "440", "Time counted from round start before CI soldiers are allowed to spawn")
br2_add_cvar("br2_time_008_open", "200", "After x seconds 008 opens automatically")
br2_add_cvar("br2_time_unlock_scps", "25", "Time after the round start when SCP containment cells unlock")
br2_add_cvar("br2_time_nuke", "90", "Time after which the nuke explodes")
br2_add_cvar("br2_time_decontamination", "65", "Time for the LCZ deconatamination to start in % of round time")
br2_add_cvar("br2_time_toggle_lockdowns", "35", "Percentage of the round time until it's possible to toggle lockdowns via terminals")

br2_add_cvar("br2_researcher_ci_percentage", "25", "Percentage of researchers that spawn as CI spies")
br2_add_cvar("br2_researcher_ci_chance", "50", "Chance for a researcher designated to be a spy to actually spawn as one")

br2_add_cvar("br2_enable_hunger", "0", "Enable the hunger system")
br2_add_cvar("br2_enable_thirst", "0", "Enable the hunger system")
br2_add_cvar("br2_enable_npcs", "1", "Enable npcs spawning")
br2_add_cvar("br2_enable_sprays", "1", "Enable sprays")
br2_add_cvar("br2_chance_to_get_downed", "50", "Chances to down a player, from 0 to 100")
br2_add_cvar("br2_chance_res_conffolder_spawn", "30", "Chance for a researcher to get a confidential folder on spawn")
br2_add_cvar("br2_down_players", "1", "Disable downing completely")
br2_add_cvar("br2_gun_damage", "0.7", "Multiplies damage dealt with guns")
br2_add_cvar("br2_sanity_change_mul", "1", "Multiplier of sanity changes")
br2_add_cvar("br2_sanity_change_interval", "3", "Delay between sanity drains in s (lower is faster)")
br2_add_cvar("br2_temperature_change_interval", "0.75", "Delay between temperature changes in seconds (lower is faster)")
br2_add_cvar("br2_temperature_high_enabled", "0", "Enable warm/high temperatures")
br2_add_cvar("br2_npc_teleport_cooldown_global", "40", "Global cooldown between SCP teleports")
br2_add_cvar("br2_npc_teleport_cooldown", "40", "Cooldown between individual SCP NPC's teleports")
br2_add_cvar("br2_035_decay_interval", "5", "Every how many seconds drain 1% of SCP-035's health")

br2_add_cvar("br2_debug_mode", "0", "Enable the debug mode")
br2_add_cvar("br2_testing_mode", "0", "Enable the testing mode")
