
br2_add_cvar("br2_time_preparing", "25", "Length of the preparing phase, in seconds")
br2_add_cvar("br2_time_round", "1320", "Length of the round, in seconds")
br2_add_cvar("br2_time_postround", "30", "Length of the post-round phase, in seconds")
br2_add_cvar("br2_time_mtf_spawn", "400", "Time after the round start before MTF support spawns unlock, in seconds")
br2_add_cvar("br2_time_ci_spawn", "440", "Time after the round start before CI support spawns unlock, in seconds")
br2_add_cvar("br2_time_008_open", "200", "Time after the round start before SCP-008 opens automatically, in seconds")
br2_add_cvar("br2_time_unlock_scps", "25", "Time after the round start before SCP containment cells unlock, in seconds")
br2_add_cvar("br2_time_nuke", "90", "Time between arming the nuke and the detonation, in seconds")
br2_add_cvar("br2_time_decontamination", "65", "Point of the round at which the LCZ decontamination starts, in % of the round length")
br2_add_cvar("br2_time_toggle_lockdowns", "35", "Point of the round after which lockdowns can be toggled from terminals, in % of the round length")

br2_add_cvar("br2_researcher_ci_percentage", "25", "Percentage of researchers designated as CI spies")
br2_add_cvar("br2_researcher_ci_chance", "50", "Chance for a designated researcher to actually spawn as a CI spy, from 0 to 100")

br2_add_cvar("br2_enable_hunger", "0", "Enable the hunger system")
br2_add_cvar("br2_enable_thirst", "0", "Enable the thirst system")
br2_add_cvar("br2_enable_npcs", "1", "Enable NPC spawning")
br2_add_cvar("br2_enable_sprays", "1", "Enable player sprays")
br2_add_cvar("br2_chance_to_get_downed", "50", "Chance for a player to get downed instead of killed, from 0 to 100")
br2_add_cvar("br2_chance_res_conffolder_spawn", "30", "Chance for a researcher to spawn with a confidential folder, from 0 to 100")
br2_add_cvar("br2_down_players", "1", "Enable downing players instead of killing them outright")
br2_add_cvar("br2_gun_damage", "0.7", "Multiplier of the damage dealt with guns")
br2_add_cvar("br2_sanity_change_mul", "1", "Multiplier of all sanity changes")
br2_add_cvar("br2_sanity_change_interval", "3", "Delay between sanity drains, in seconds (lower is faster)")
br2_add_cvar("br2_temperature_change_interval", "0.75", "Delay between temperature changes, in seconds (lower is faster)")
br2_add_cvar("br2_temperature_high_enabled", "0", "Enable warm and hot temperatures")
br2_add_cvar("br2_npc_teleport_cooldown_global", "40", "Cooldown between any two SCP NPC teleports, in seconds")
br2_add_cvar("br2_npc_teleport_cooldown", "40", "Cooldown between teleports of a single SCP NPC, in seconds")
br2_add_cvar("br2_035_decay_interval", "5", "Delay between draining 1% of SCP-035's health, in seconds")

br2_add_cvar("br2_debug_mode", "0", "Enable the debug mode")
br2_add_cvar("br2_testing_mode", "0", "Enable the testing mode")
