
BR_DEFAULT_OUTFIT = {
	name = "Casual Clothes",
	model = "",
	temp_resistance = OUTFIT_COLD_RESISTANCE_LOW,
	walk_speed = 1,
	run_speed = 1,
	jump_power = 1,
	bullet_damage = 1,
	fire_damage = 1,
	explosion_damage = 1,
	can_change_outfits = false,
	can_loot_this_outfit = false,
	footstep_volume = 1,
	player_color = Color(2,59,106,255),
	hands = {mdl = "models/weapons/c_arms_citizen.mdl", skin = 0},
	examine = "You are wearing casual clothes",
}

BREACH_OUTFITS = {
	{
		class = "scp_049",
		name = "SCP-049's Outfit",
		model = "models/breach2_models/scp_049.mdl",
		temp_resistance = OUTFIT_COLD_RESISTANCE_MEDIUM,
		walk_speed = 0.94,
		run_speed = 0.8,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = false,
		can_loot_this_outfit = false,
		footstep_volume = 1.2,
		footstep_sounds = {
			{"breach2/scp/049/Step1.ogg", 1},
			{"breach2/scp/049/Step2.ogg", 1},
			{"breach2/scp/049/Step3.ogg", 1},
		},
		player_color = Vector(255,0,0,255),
		hands = {mdl = "models/vinrax/weapons/c_arms_scp049.mdl", skin = 0},
		examine = "You are wearing your doctor clothes, they slow you a bit but give you protection",
		examine_info = " - It looks like SCP-049!"
	},
	{
		class = "scp_0492",
		name = "SCP-049-2's Default Outfit",
		model = "models/player/zombie_classic.mdl", -- TODO
		temp_resistance = OUTFIT_COLD_RESISTANCE_MEDIUM,
		walk_speed = 0.85,
		run_speed = 0.85,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = false,
		can_loot_this_outfit = false,
		footstep_volume = 1.2,
		footstep_sounds = {
			{"breach2/scp/049/Step1.ogg", 1},
			{"breach2/scp/049/Step2.ogg", 1},
			{"breach2/scp/049/Step3.ogg", 1},
		},
		player_color = Vector(255,0,0,255),
		hands = {mdl = "models/weapons/c_arms_citizen.mdl", skin = 0},
		examine = "You are wearing the clothes you have worn before...",
		examine_info = " - It looks like SCP-049-2!"
	},
	{
		class = "scp_173",
		name = "SCP-173's Outfit",
		model = SCP_173_MODEL,
		temp_resistance = OUTFIT_COLD_RESISTANCE_VERYHIGH,
		--disable_movement = true,
		disable_movement = false,
		walk_speed = 1,
		run_speed = 1,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = false,
		can_loot_this_outfit = false,
		footstep_volume = 1,
		examine_info = " - It looks like SCP-173!"
	},
	{
		class = "class_d",
		name = "Orange Jumpsuit",
		model = {
			"models/player/kerry/class_d_1.mdl",
			"models/player/kerry/class_d_2.mdl",
			"models/player/kerry/class_d_3.mdl",
			"models/player/kerry/class_d_4.mdl",
			"models/player/kerry/class_d_5.mdl",
			"models/player/kerry/class_d_6.mdl",
			"models/player/kerry/class_d_7.mdl",
		},
		temp_resistance = OUTFIT_COLD_RESISTANCE_LOW,
		walk_speed = 1.05,
		run_speed = 1.05,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 0.95,
		player_color = Color(244,152,66,255),
		hands = {mdl = "models/weapons/c_arms_citizen.mdl", skin = 0},
		examine = "You are wearing an Orange Jumpsuit",
		examine_info = " - They look like a Class D"
	},
	{
		class = "scientist",
		name = "Scientist Outfit",
		model = {
			"models/player/kerry/class_scientist_1.mdl",
			"models/player/kerry/class_scientist_2.mdl",
			"models/player/kerry/class_scientist_3.mdl",
			"models/player/kerry/class_scientist_4.mdl",
			"models/player/kerry/class_scientist_5.mdl",
			"models/player/kerry/class_scientist_6.mdl",
			"models/player/kerry/class_scientist_7.mdl",
		},
		temp_resistance = OUTFIT_COLD_RESISTANCE_VERYLOW,
		walk_speed = 1,
		run_speed = 1,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 0.95,
		player_color = Color(255,255,255,255),
		hands = {mdl = "models/weapons/c_arms_citizen.mdl", skin = 0},
		examine = "You are wearing a Scientist Outfit",
		examine_info = " - They look like a Researcher"
	},
	{
		class = "janitor",
		name = "Janitor Suit",
		model = {
			--"models/player/group01/male_01.mdl",
			"models/player/group01/male_02.mdl",
			--"models/player/group01/male_03.mdl",
			"models/player/group01/male_04.mdl",
			"models/player/group01/male_05.mdl",
			"models/player/group01/male_06.mdl",
			"models/player/group01/male_07.mdl",
			"models/player/group01/male_08.mdl",
			"models/player/group01/male_09.mdl",
		},
		temp_resistance = OUTFIT_COLD_RESISTANCE_LOW,
		walk_speed = 1,
		run_speed = 1,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 1,
		player_color = Color(2,59,106,255),
		hands = {mdl = "models/weapons/c_arms_refugee.mdl", skin = 0},
		examine = "You are wearing a Janitor Suit",
		examine_info = " - They look like a Janitor"
	},
	{
		class = "engineer",
		name = "Engineer Suit",
		model = {
			"models/player/hostage/hostage_01.mdl",
			"models/player/hostage/hostage_02.mdl",
			"models/player/hostage/hostage_03.mdl",
			"models/player/hostage/hostage_04.mdl"
		},
		temp_resistance = OUTFIT_COLD_RESISTANCE_MEDIUM,
		walk_speed = 0.95,
		run_speed = 1,
		jump_power = 0.97,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 1,
		player_color = Color(194,145,0,255),
		hands = {mdl = "models/weapons/c_arms_refugee.mdl", skin = 0},
		examine = "You are wearing an Engineer Suit",
		examine_info = " - They look like an Engineer"
	},
	{
		class = "medic",
		name = "Medical Uniform",
		model = {
			--"models/redninja/pmedic01.mdl",
			--"models/redninja/pmedic02.mdl",
			"models/player/kerry/medic/medic_01.mdl",
			"models/player/kerry/medic/medic_02.mdl",
			"models/player/kerry/medic/medic_03.mdl",
			"models/player/kerry/medic/medic_04.mdl",
			"models/player/kerry/medic/medic_05.mdl",
			"models/player/kerry/medic/medic_06.mdl",
			"models/player/kerry/medic/medic_07.mdl",
		},
		temp_resistance = OUTFIT_COLD_RESISTANCE_LOW,
		walk_speed = 1,
		run_speed = 1,
		jump_power = 1,
		bullet_damage = 1,
		fire_damage = 1,
		explosion_damage = 1,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 0.95,
		player_color = Color(21,122,147,255),
		hands = {mdl = "models/weapons/c_arms_citizen.mdl", skin = 0},
		examine = "You are wearing a Medical Uniform",
		examine_info = " - They look like a Doctor"
	},
	{
		class = "hazmat",
		name = "Hazmat Suit",
		model = "models/hazmat/bmhaztechs.mdl",
		temp_resistance = OUTFIT_COLD_RESISTANCE_VERYHIGH,
		walk_speed = 0.95,
		run_speed = 0.95,
		jump_power = 0.95,
		bullet_damage = 1,
		fire_damage = 0.5,
		explosion_damage = 0.75,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		has_gasmask = true,
		footstep_volume = 1.1,
		player_color = Color(255,255,255,255),
		hands = {mdl = "models/weapons/c_arms_cstrike_2.mdl", skin = 0},
		examine = "You are wearing a Hazmat Suit, its heavy and hot but gives you protection",
		examine_info = " - They look like a Containment Specialist"
	},
	{
		class = "guard",
		name = "Guard Uniform",
		model = "models/fart/ragdolls/css/counter_gign_player.mdl",
		temp_resistance = OUTFIT_COLD_RESISTANCE_HIGH,
		walk_speed = 0.95,
		run_speed = 0.95,
		jump_power = 0.95,
		bullet_damage = 0.9,
		fire_damage = 0.9,
		explosion_damage = 0.9,
		can_change_outfits = true,
		can_loot_this_outfit = true,
		footstep_volume = 1.1,
		player_color = Color(50,50,50,255),
		hands = {mdl = "models/weapons/c_arms_cstrike_2.mdl", skin = 0},
		examine = "You are wearing a Guard Uniform which gives you protection",
		examine_info = " - They look like a Guard"
	},
	{
		class = "ci_soldier",
		name = "Soldier Uniform",
		model = "models/mw2/skin_03/mw2_soldier_04.mdl",
		temp_resistance = OUTFIT_COLD_RESISTANCE_VERYHIGH,
		walk_speed = 0.95,
		run_speed = 0.95,
		jump_power = 0.95,
		bullet_damage = 0.8,
		fire_damage = 0.9,
		explosion_damage = 0.9,
		can_change_outfits = false,
		can_loot_this_outfit = true,
		footstep_volume = 1.25,
		player_color = Color(50,50,50,255),
		hands = {mdl = "models/weapons/c_arms_cstrike_3.mdl", skin = 0},
		examine = "You are wearing a Soldier Uniform which gives you a lot of protection",
		examine_info = " - They look like a Soldier"
	},
	{
		class = "mtf",
		name = "MTF Uniform",
		model = "models/mtf/mtf remasteredhd.mdl",
		temp_resistance = OUTFIT_COLD_RESISTANCE_VERYHIGH,
		walk_speed = 0.96,
		run_speed = 0.96,
		jump_power = 0.96,
		bullet_damage = 0.8,
		fire_damage = 0.9,
		explosion_damage = 0.9,
		can_change_outfits = false,
		can_loot_this_outfit = true,
		footstep_volume = 1.25,
		player_color = Color(50,50,50,255),
		hands = {mdl = "models/weapons/c_arms_cstrike_3.mdl", skin = 0},
		examine = "You are wearing a MTF Uniform which gives you a lot of protection",
		examine_info = " - They look like a Soldier"
	},
}

print("[Breach2] config/sh_outfits.lua loaded!")
