
util.AddNetworkString("br_send_notepad")
util.AddNetworkString("br_send_info")
util.AddNetworkString("br_spotted")
util.AddNetworkString("br_keypad")
util.AddNetworkString("br_playsound")
util.AddNetworkString("bnet_send_netvar")
util.AddNetworkString("bnet_send_netvar_remove")
util.AddNetworkString("br_round_start")
util.AddNetworkString("br_round_prepstart")
util.AddNetworkString("br_round_info")
util.AddNetworkString("br_open_terminal")
util.AddNetworkString("br_open_brokenterminal")
util.AddNetworkString("br_update_health_state")
util.AddNetworkString("br_player_downed")
util.AddNetworkString("br_check_pulse")
util.AddNetworkString("br_start_reviving")
util.AddNetworkString("br_end_reviving")
util.AddNetworkString("br_start_checking_pulse")
util.AddNetworkString("br_end_checking_pulse")
util.AddNetworkString("br_is_reviving")
util.AddNetworkString("br_use_camera")
util.AddNetworkString("br_stop_using_camera")
util.AddNetworkString("br_update_sanity")
util.AddNetworkString("br_use_medkit_item")
util.AddNetworkString("br_c4_action")
util.AddNetworkString("br_action")
util.AddNetworkString("br_update_bleeding")
util.AddNetworkString("br_get_loot_info")
util.AddNetworkString("br_take_loot")
util.AddNetworkString("br_drop_weapon")
util.AddNetworkString("br_pickup_item")
util.AddNetworkString("br_updatecode_radio")
util.AddNetworkString("br_updatebattery")
util.AddNetworkString("br_update_own_info")
util.AddNetworkString("br_retrieve_own_notes")
util.AddNetworkString("br_get_body_notepad")
util.AddNetworkString("br_loot_container")
util.AddNetworkString("br_loot_crate")
util.AddNetworkString("br_use_button_simple")
util.AddNetworkString("br_use_outfitter")
util.AddNetworkString("br_take_outfit")
util.AddNetworkString("scp_012_seen")
util.AddNetworkString("cl_playerdeath")
util.AddNetworkString("br_pregame_spawns")
util.AddNetworkString("br_update_support_spawns")
util.AddNetworkString("cl_playerescaped")
util.AddNetworkString("br_support_spawn")
util.AddNetworkString("br_mtf_teams_update")
util.AddNetworkString("br_mtf_teams_join")
util.AddNetworkString("br_mtf_teams_leave")
util.AddNetworkString("br_mtf_team_ready")
util.AddNetworkString("br_get_special_items")
util.AddNetworkString("br_get_owned_devices")
util.AddNetworkString("br_get_terminal_settings")
util.AddNetworkString("br_drop_special_item")
util.AddNetworkString("br_use_special_item")
util.AddNetworkString("br_force_print_name")
util.AddNetworkString("br_use_soda_machine")
util.AddNetworkString("br_install_device")
util.AddNetworkString("br_use_294")
util.AddNetworkString("br_use_document")
util.AddNetworkString("br_update_hunger")
util.AddNetworkString("br_use_terminal_function")
util.AddNetworkString("br_enable_primary_lights")
util.AddNetworkString("br_disable_primary_lights")
util.AddNetworkString("br_vote_round_end")
util.AddNetworkString("br_send_crate_info")
util.AddNetworkString("br_hide_in_closet")
util.AddNetworkString("br_update_misc")
util.AddNetworkString("br_scp173_mode")
util.AddNetworkString("br2_notification")
util.AddNetworkString("br_check_someones_notepad")
util.AddNetworkString("br_hack_terminal")
util.AddNetworkString("br_scp_action")
util.AddNetworkString("br_custom_screen_effects")
util.AddNetworkString("br_blinking")
util.AddNetworkString("br_getlightlevel")
util.AddNetworkString("br_closed_294")
util.AddNetworkString("br_send_nvg_entities")

include("net_supports.lua") -- top priority

include("net_health.lua")
include("net_items.lua")
include("net_looting.lua")
include("net_outfits.lua")
include("net_player_actions.lua")
include("net_round.lua")
include("net_terminal.lua")
include("net_scp.lua")
include("net_country_codes.lua")
include("net_notification.lua")
include("net_scp_actions.lua")
include("net_screen_effects.lua")

include("tick.lua") -- lowest priority

net.Receive("br_getlightlevel", function(len, ply)
    if len < 1024 then
	    ply.lightLevel = net.ReadFloat()
    end
end)

print("[Breach2] server/networking/init.lua loaded!")
