
GAMESTATE_NOTSTARTED = 0
GAMESTATE_STARTING = 1
GAMESTATE_PREPARING = 2
GAMESTATE_ROUND = 3
GAMESTATE_POSTROUND = 4
GAMESTATE_ROUND_END = 5

TEAM_CLASSD = 3
TEAM_MINORSTAFF = 4
TEAM_RESEARCHER = 5
TEAM_SECURITY = 6
TEAM_MTF = 7
TEAM_SCP = 8
TEAM_CI = 9

SUPPORT_NONE = 1
SUPPORT_ROGUE = 2
SUPPORT_FOUNDATION = 3
SUPPORT_CI = 4

HEALTH_ALIVE = 1
HEALTH_MISSING = 2
HEALTH_DEAD = 3

TEAM_ALIVE = 1

VALUE_ANGLE  = 1
VALUE_BOOL   = 2
VALUE_COLOR  = 3
VALUE_DOUBLE = 4
VALUE_ENTITY = 5
VALUE_FLOAT  = 6
VALUE_INT    = 7
VALUE_NORMAL = 8
VALUE_STRING = 9
VALUE_TABLE  = 10
VALUE_UINT   = 11
VALUE_VECTOR = 12

ZONE_TEMP_NORMAL = 1
ZONE_TEMP_WARM = 2
ZONE_TEMP_HOT = 3
ZONE_TEMP_COLD = 4
ZONE_TEMP_VERYCOLD = 5

OUTFIT_COLD_RESISTANCE_VERYLOW = 1
OUTFIT_COLD_RESISTANCE_LOW = 2
OUTFIT_COLD_RESISTANCE_MEDIUM = 3
OUTFIT_COLD_RESISTANCE_HIGH = 4
OUTFIT_COLD_RESISTANCE_VERYHIGH = 5

SCP294_RESULT_OUTOFRANGE = 1
SCP294_RESULT_NOTHING = 2
SCP294_RESULT_NORMAL = 3
SCP294_RESULT_STRUGGLING = 4
SCP294_RESULT_INSANE = 5

print("[Breach2] shared/sh_enums.lua loaded!")
