
GM_VERSION = "0.3"
GM_VERSION_GROUP = "Alpha"
GM_VERSION_NUM = 0.3

GAMESTATE_NOTSTARTED = 0
GAMESTATE_PREPARING = 1
GAMESTATE_ROUND = 2
GAMESTATE_POSTROUND = 3
GAMESTATE_ROUND_END = 4

TEAM_CLASSD = 3
TEAM_MINORSTAFF = 4
TEAM_RESEARCHER = 5
TEAM_SECURITY = 6
TEAM_MTF = 7
TEAM_SCP = 8
TEAM_CI = 9

SUPPORT_NONE = 1
SUPPORT_ROGUE = 2
SUPPORT_FOUNDATION = 3
SUPPORT_CI = 4

DEF_SLOWWALKSPEED = 80
DEF_WALKSPEED = 130
DEF_RUNSPEED = 220
DEF_JUMPPOWER = 160

DEF_FOV = 84

FOG_LEVEL = 1000 -- 1000
DEF_PLAYER_RANGE = FOG_LEVEL - 20

HEALTH_ALIVE = 1
HEALTH_MISSING = 2
HEALTH_DEAD = 3

TEAM_ALIVE = 1

VALUE_ANGLE  = 1
VALUE_BOOL   = 2
VALUE_COLOR  = 3
VALUE_DOUBLE = 4
VALUE_ENTITY = 5
VALUE_FLOAT  = 6
VALUE_INT    = 7
VALUE_NORMAL = 8
VALUE_STRING = 9
VALUE_TABLE  = 10
VALUE_UINT   = 11
VALUE_VECTOR = 12

ZONE_TEMP_NORMAL = 1
ZONE_TEMP_WARM = 2
ZONE_TEMP_HOT = 3
ZONE_TEMP_COLD = 4
ZONE_TEMP_VERYCOLD = 5

OUTFIT_COLD_RESISTANCE_VERYLOW = 1
OUTFIT_COLD_RESISTANCE_LOW = 2
OUTFIT_COLD_RESISTANCE_MEDIUM = 3
OUTFIT_COLD_RESISTANCE_HIGH = 4
OUTFIT_COLD_RESISTANCE_VERYHIGH = 5

SCP_173_MODEL = "models/breach2_models/scp_173.mdl"

NAMES_TEAM_CI = {
	"Hydra",
	"Aion",
	"Hemera",
	"Ares",
	"Ourea",
	"Thor",
}

print("[Breach2] shared/sh_enums.lua loaded!")
